# Generated by Django 6.0.1 on 2026-01-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
