# Generated by Django 6.0.1 on 2026-02-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_studentmodel_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='regd_no',
            field=models.IntegerField(null=True),
        ),
    ]
