# Generated by Django 6.0.1 on 2026-02-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_studentmodel_regd_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
