# Generated by Django 6.0.1 on 2026-01-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitmodel',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
